#
---
PMID:
  - '^\d+?$'
  - PMID
pmc:
  - '^PMC\d+?$'
  - pmc
geogsm:
  - '^GSM\d+?$'
  - geogsm
geogse:
  - '^GSE\d+?$'
  - geogse
geogpl:
  - '^GPL\d+?$'
  - geogpl
egastudy:
  - '^EGAS\d{11}$'
  - ega.study
egadataset:
  - '^EGAD\d{11}$'
  - ega.dataset
biostudies:
  - '^S\-\w+?\d+?$'
  - biostudies
cellosaurus:
  - 'CVCL_[A-Z0-9]{4}'
  - cellosaurus
