#
---
dataset_names:
  - arraymap
  - progenetix
  - tcga
  - dipg
collection_names:
  - variants
  - callsets
  - biosamples
  - individuals
  - biosubsets
  - datacollections

biosubsets:
  NCIT:
    label: 'NCIt Neoplasm Code'
    prefix: NCIT
    pattern: '^(ncit\:)?C\d+?$'
    greedymatch: '^(NCIT\:)?C\d+?$'
  icdom:
    label: 'ICD-O 3 Morphology Code'
    prefix: icdom
    pattern: '^icdom\-\d{5}$'
    greedymatch: '^icdom\-\d{1,5}$'
  icdot:
    label: 'ICD-O 3 Organ Site Code'
    prefix: icdot
    pattern: '^icdot\-C\d{1,2}\.\d$'
    greedymatch: '^icdot\-?C\d\d?(\.\d)?$'
  seer:
    label: 'SEER Code'
    prefix: seer
    pattern: '^seer\:\d{5}$'
    greedymatch: '^seer\:\d{1,5}$'

datacollections:
  PMID:
    label: 'Pubmed Publication'
    prefix: PMID
    pattern: '^PMID\:\d{6,8}$'
    greedymatch: '^pubmed\:\d{1,8}$'
  pgxdx:
    label: 'Progenetix Diagnostic Group'
    prefix: pgxdx
    pattern: '^(pgxdx\:)?[\w\[\] \:\-]{5,255}$'
    greedymatch: '^(pgxdx\:)?[\w\[\] \:\-]{5,255}$'
  cellosaurus:
    label: 'Cellline ID'
    prefix: cellosaurus
    pattern: '^(cellosaurus\:)?CVCL_[A-Z0-9]{4}$'
    greedymatch: '^(cellosaurus\:)?CVCL(_([A-Z0-9]{1,4})?)?$'
  geogse:
    label: 'NCBI Gene Expression Omnibus series'
    prefix: geo
    pattern: '^geogse\-GSE\d+?$'
    greedymatch: '^geogse\-GSE\d*?$'
  geogpl:
    label: 'NCBI Gene Expression Omnibus platform'
    prefix: geo
    pattern: '^geogpl\-GPL\d+?$'
    greedymatch: '^geogpl-GPL\d*?$'
  egastudy:
    label: 'EGA Study'
    prefix: 'ega.study'
    pattern: '^(ega.study\:)?EGAS\d{11}$'
    greedymatch: '^(ega.study\:)?EGAS\d{1,11}$'

genome_assemblies:
  - 'GRCh38'
paths:
  dir_ontology_maps: 'ICDOntologies/current'
